; Script generated by the Inno Setup Script Wizard.
; For more information, please visit: https://jrsoftware.org/isinfo.php

[Setup]
; App Information
AppId={{e72b26bc-2aad-4814-acff-732ac5daff35}
AppName=MPA
AppVersion=2.25.826
AppPublisher=IbrahimND (Ebrahim Namdari)
AppPublisherURL=https://github.com/IbrahimNamdari/My-Portable-Apps
AppSupportURL=https://github.com/IbrahimNamdari/My-Portable-Apps
AppUpdatesURL=https://github.com/IbrahimNamdari/My-Portable-Apps

; Installation Directories
DefaultDirName={autopf}\MPA
DefaultGroupName=MPA

; Output and Security
OutputBaseFilename=MPA-Installer-2.25.826
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
SetupIconFile=.\icon32.ico
UninstallDisplayIcon={app}\main.exe

; Additional Options
DisableStartupPrompt=yes

[Tasks]
Name: desktopicon; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:";
Name: runonstartup; Description: "Run MPA when Windows starts"; GroupDescription: "Additional options:";

[Files]
; Main executable
Source: "dist\main.exe"; DestDir: "{app}"; Flags: ignoreversion

; Other directories and files
Source: "img\*"; DestDir: "{app}\img"; Flags: recursesubdirs createallsubdirs
Source: "otherapps\*"; DestDir: "{app}\otherapps"; Flags: recursesubdirs createallsubdirs
Source: "core\model\data\*"; DestDir: "{app}\core\model\data"; Flags: recursesubdirs createallsubdirs
Source: "ui\*"; DestDir: "{app}\ui"; Flags: recursesubdirs createallsubdirs

[Icons]
; Start Menu icon
Name: "{group}\MPA"; Filename: "{app}\main.exe"
; Uninstall icon
Name: "{group}\Uninstall MPA"; Filename: "{uninstallexe}"
; Desktop icon (optional)
Name: "{autodesktop}\MPA"; Filename: "{app}\main.exe"; Tasks: desktopicon
; Startup icon (optional)
Name: "{autostartup}\MPA"; Filename: "{app}\main.exe"; Tasks: runonstartup

[Run]
; Launch the application after installation
Filename: "{app}\main.exe"; Description: "{cm:LaunchProgram,MPA}"; Flags: nowait postinstall