# Form implementation generated from reading ui file 'wifiList_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_wifiList(object):
    def setupUi(self, wifiList):
        wifiList.setObjectName("wifiList")
        wifiList.resize(500, 509)
        wifiList.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily("IRANSansWeb(FaNum)")
        font.setPointSize(16)
        wifiList.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(wifiList)
        self.gridLayout.setObjectName("gridLayout")
        self.chooseWifiButton = QtWidgets.QPushButton(parent=wifiList)
        self.chooseWifiButton.setMinimumSize(QtCore.QSize(0, 50))
        self.chooseWifiButton.setObjectName("chooseWifiButton")
        self.gridLayout.addWidget(self.chooseWifiButton, 2, 0, 1, 1)
        self.deleteWifiButton = QtWidgets.QPushButton(parent=wifiList)
        self.deleteWifiButton.setMinimumSize(QtCore.QSize(0, 50))
        self.deleteWifiButton.setObjectName("deleteWifiButton")
        self.gridLayout.addWidget(self.deleteWifiButton, 0, 1, 1, 1)
        self.wifiTableView = QtWidgets.QTableView(parent=wifiList)
        font = QtGui.QFont()
        font.setFamily("IRANSansWeb(FaNum)")
        font.setPointSize(14)
        self.wifiTableView.setFont(font)
        self.wifiTableView.setObjectName("wifiTableView")
        self.gridLayout.addWidget(self.wifiTableView, 1, 0, 1, 2)
        self.wifiListLabel = QtWidgets.QLabel(parent=wifiList)
        self.wifiListLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.wifiListLabel.setObjectName("wifiListLabel")
        self.gridLayout.addWidget(self.wifiListLabel, 0, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(parent=wifiList)
        self.cancel.setMinimumSize(QtCore.QSize(0, 50))
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 2, 1, 1, 1)

        self.retranslateUi(wifiList)
        QtCore.QMetaObject.connectSlotsByName(wifiList)

    def retranslateUi(self, wifiList):
        _translate = QtCore.QCoreApplication.translate
        wifiList.setWindowTitle(_translate("wifiList", "Wi-Fi List"))
        self.chooseWifiButton.setText(_translate("wifiList", "Choos Wi-Fi"))
        self.deleteWifiButton.setText(_translate("wifiList", "Delete Wi-Fi From List"))
        self.wifiListLabel.setText(_translate("wifiList", "Wi-Fi List"))
        self.cancel.setText(_translate("wifiList", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wifiList = QtWidgets.QDialog()
    ui = Ui_wifiList()
    ui.setupUi(wifiList)
    wifiList.show()
    sys.exit(app.exec())
